### ISSUE TITLE
additional activities

### ISSUE THREAD

**Issue by BerndKohl** [ianperrin/MMM-Strava#37]
Feature request / Question:
Is it possible to retrieve additional activities (besides running, swimming, cycling) from Strava and display them on the mirror?

If so, how?

**Comment by khassel** [comment]
I think this should already work in `chart` mode. You can find the activity types [here](https://developers.strava.com/docs/reference/#api-models-ActivityType).

In `table` mode this is not simple because the used [athletes stats object](https://developers.strava.com/docs/reference/#api-Athletes-getStats) only provides these infos:
```json
{
  "recent_run_totals" : "",
  "all_run_totals" : "",
  "recent_swim_totals" : "",
  "biggest_ride_distance" : 0.8008281904610115,
  "ytd_swim_totals" : "",
  "all_swim_totals" : "",
  "recent_ride_totals" : {
    "distance" : 5.962134,
    "achievement_count" : 9,
    "count" : 1,
    "elapsed_time" : 2,
    "elevation_gain" : 7.0614014,
    "moving_time" : 5
  },
  "biggest_climb_elevation_gain" : 6.027456183070403,
  "ytd_ride_totals" : "",
  "all_ride_totals" : "",
  "ytd_run_totals" : ""
}
```

**Comment by BerndKohl** [comment]
Thanks, would have loved to see it in table mode - which is - if I read this correctly - not supported by the Strava API.
